### ISSUE TITLE
Unexpected HTTP server response - needs 200 got 403

### ISSUE THREAD

**Issue by cbogithub** [tejado/pgoapi#160] opened 2016-07-31 12:58 UTC
python2.7 pokecli.py
2016-07-31 12:54:37,971 [    pgoapi] [ INFO] pgoapi v1.1.5 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-07-31 12:54:38,013 [ utilities] [ INFO] Location for 'Sydney, New South Wales, Australia' found: Sydney NSW, Australia
2016-07-31 12:54:38,013 [ utilities] [ INFO] Coordinates (lat/long/alt) for location: -33.8688197 151.2092955 0.0
2016-07-31 12:54:38,014 [  auth_ptc] [ INFO] Login for: xxxxxxxxxxxxx
2016-07-31 12:54:38,596 [  auth_ptc] [ INFO] PTC Login successful
2016-07-31 12:54:38,596 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-31 12:54:38,596 [    pgoapi] [ INFO] Creating a new request...
2016-07-31 12:54:38,596 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-31 12:54:38,597 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
2016-07-31 12:54:38,597 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-07-31 12:54:38,597 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-07-31 12:54:38,597 [    pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-07-31 12:54:38,598 [    pgoapi] [ INFO] Execution of RPC
2016-07-31 12:54:38,681 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403
Traceback (most recent call last):
  File "pokecli.py", line 139, in <module>
    main()
  File "pokecli.py", line 119, in main
    if not api.login(config.auth_service, config.username, config.password, app_simulation = True):
  File "/home/pgoapi/pgoapi/pgoapi.py", line 126, in login
    response = request.call()
  File "/home/pgoapi/pgoapi/pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/pgoapi/pgoapi/rpc_api.py", line 108, in request
    if ('auth_ticket' in response_dict) and ('expire_timestamp_ms' in response_dict['auth_ticket']) and (self._auth_provider.is_new_ticket(response_dict['auth_ticket']['expire_timestamp_ms'])):
TypeError: argument of type 'bool' is not iterable

**Comment by genIterator** [comment] 2016-07-31 14:34
Which server provider are you using?
Niantic blocks certain cloud computing providers after the new update.
There are several threads on github on this, like:
https://www.reddit.com/r/pokemongodev/comments/4vf6vu/api_not_working403_error/

**Comment by tejado** [comment] 2016-08-01 14:23
Duplicate of https://github.com/tejado/pgoapi/issues/151

**Closed by tejado** 2016-08-01 14:23 UTC
Labels: duplicate
